#include<avr/io.h>
#include<util/delay.h>

main()
{
  DDRC = 0xff;    // 0xff = 0b11111111 and 0x00 = 0b00000000
  int a[5]={10,20,30,40,50};   // Random patterns will be generated by using these numbers corrsponding binary values
  
  for(int i=0;i<5;i++)
  {
    PORTC = a[i];
	_delay_ms(1000);
  }
}